%% ============================================================
%  CARACTERIZACIÓN DE LOS LÁSERES
%  ============================================================

clear;
close all;
clc;

% Estilo general
set(groot, ...
    'defaultAxesFontName', 'Arial', ...
    'defaultAxesFontSize', 13, ...
    'defaultAxesLineWidth', 1.0, ...
    'defaultLineLineWidth', 2.0, ...
    'defaultTextFontName', 'Arial');

% Colores
purple = [128 0 128] / 255;
red    = [198 40 40] / 255;
green  = [46 139 87] / 255;
cyan   = [23 190 207] / 255;
black  = [0.15 0.15 0.15];


%% ============================================================
% 1. LÁSER FPL1053S
% Comparación entre dos medidores
% =============================================================

x = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, ...
     100, 150, 200, 300, 400];


y_dBm1 = [-49.54, -38.99, -14.61, -8.76, -6.52, -4.88, ...
          -3.79, -2.79, -2.01, -1.45, 0.94, 2.21, ...
          4.26, 5.78];

y_dBm2 = [-49.53, -38.99, -15.05, -8.78, -6.71, -5.17, ...
          -3.94, -3.04, -2.25, -1.59, 0.65, 1.96, ...
          3.89, 5.18];

atenuacion = 15;       % dB compensados

y_mW1 = TransformUnits(y_dBm1, atenuacion);
y_mW2 = TransformUnits(y_dBm2, atenuacion);


% Solo se representan los pares x-y disponibles

x_plot1 = x(1:length(y_mW1));
x_plot2 = x(1:length(y_mW2));

figure('Color','w', ...
       'Units','normalized', ...
       'Position',[0.15 0.15 0.65 0.65]);

hold on;
grid on;
box off;

plot(x_plot1, y_mW1, ...
    '-o', ...
    'Color', red, ...
    'LineWidth', 2.2, ...
    'MarkerSize', 6.5, ...
    'MarkerFaceColor', cyan, ...
    'MarkerEdgeColor', red);

plot(x_plot2, y_mW2, ...
    '-o', ...
    'Color', purple, ...
    'LineWidth', 2.2, ...
    'MarkerSize', 6.5, ...
    'MarkerFaceColor', cyan, ...
    'MarkerEdgeColor', purple);

yline(y_mW1(end), ...
    '--', ...
    'Color', black, ...
    'LineWidth', 1.5);

yline(y_mW2(end), ...
    '-.', ...
    'Color', black, ...
    'LineWidth', 1.5);

xlabel('Intensidad (mA)', ...
    'FontSize', 15);

ylabel('Potencia (mW)', ...
    'FontSize', 15);

title('Comparación de medidores: relación intensidad-potencia del láser FPL1053S', ...
    'FontSize', 17, ...
    'FontWeight', 'bold');

ax = gca;

ax.FontSize = 13;

ax.GridLineStyle = '--';
ax.GridAlpha = 0.20;
ax.MinorGridAlpha = 0.10;

xlim([min(x), max(x)]);
ylim padded;

legend('Primer medidor', ...
       'Segundo medidor', ...
       'Location', 'east', ...
       'FontSize', 12);

hold off;


%% ============================================================
% 2. LÁSER RIO PLANEX
% Comparación entre dos medidores
% =============================================================

x = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, ...
     100, 110, 115];

y_dBm1 = [-28.1, -21.6, -18.36, -16.00, -14.11, -12.6, ...
          -11.28, -10.18, -9.27, -8.43, -7.79, -7.47];

y_dBm2 = [-28.6, -21.99, -18.56, -16.34, -14.44, -13.06, ...
          -11.71, -10.5, -9.74, -8.91, -8.18, -7.9];

atenuacion = 20;       % dB compensados

% Conversión a mW
y_mW1 = TransformUnits(y_dBm1, atenuacion);
y_mW2 = TransformUnits(y_dBm2, atenuacion);

% Solo se representan los pares disponibles
x_plot1 = x(1:length(y_mW1));
x_plot2 = x(1:length(y_mW2));


% Figura
figure('Color','w', ...
       'Units','normalized', ...
       'Position',[0.15 0.15 0.65 0.65]);

hold on;
grid on;
box off;

% Primer medidor
plot(x_plot1, y_mW1, ...
    '-o', ...
    'Color', red, ...
    'LineWidth', 2.2, ...
    'MarkerSize', 6.5, ...
    'MarkerFaceColor', cyan, ...
    'MarkerEdgeColor', red);

% Segundo medidor
plot(x_plot2, y_mW2, ...
    '-o', ...
    'Color', purple, ...
    'LineWidth', 2.2, ...
    'MarkerSize', 6.5, ...
    'MarkerFaceColor', cyan, ...
    'MarkerEdgeColor', purple);

% Líneas de referencia
yline(y_mW1(end), ...
    '--', ...
    'Color', black, ...
    'LineWidth', 1.5);

yline(y_mW2(end), ...
    '-.', ...
    'Color', black, ...
    'LineWidth', 1.5);

% Etiquetas
xlabel('Intensidad (mA)', ...
    'FontSize', 15);

ylabel('Potencia (mW)', ...
    'FontSize', 15);

title('Comparación de medidores: relación intensidad-potencia del láser RIO PLANEX', ...
    'FontSize', 17, ...
    'FontWeight', 'bold');

% Ajustes de los ejes
ax = gca;
ax.FontSize = 13;
ax.GridLineStyle = '--';
ax.GridAlpha = 0.20;
ax.MinorGridAlpha = 0.10;

xlim([min(x), max(x)]);
ylim padded;

legend('Primer medidor', ...
       'Segundo medidor', ...
       'Location', 'east', ...
       'FontSize', 12);

hold off;

